disable_language.settings:
  type: config_object
  label: 'Disable Language settings'
  mapping:
    redirect_override_routes:
      type: array
      label: 'List of route names that will redirect to themselves in the right language instead of the frontpage when accessed in a disabled language.'
